replicaCount: 3

image:
  repository: uonyeka/canary-demo
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false

canary:
  enabled: true
  replicaCount: 1
  image:
    tag: "v3"

config:
  main:
    appColor: "blue"
    welcomeMessage: "Bienvenidos al Curso de GCP de Educación IT!"
  canary:
    appColor: "white"
    welcomeMessage: "Bienvenidos al Curso de GCP de Educación IT! Canary"

serviceMonitor:
  enabled: true

slo:
  availability:
    target: 99.9
    errorBudgetPeriod: "30d"
